name: Building

on:
  push:
    branches:
      - "testing"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Premake
        run: sudo bash ${PWD}/scripts/build-make.sh

      - name: Run
        run: ${PWD}/bin/linux-x86_64/Debug/TestBed/TestBed
