name: 'coverage'
on:
    pull_request:
        branches:
            - testing
    push:
        branches:
            - testing
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          
          - name: Upload coverage reports to Codecov
            uses: codecov/codecov-action@v4.0.1
            with:
              token: ${{ secrets.CODECOV_TOKEN }}
          - uses: cpp-linter/cpp-linter-action@v2
            id: linter
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              style: 'file'  # Use .clang-format config file
              tidy-checks: '' # Use .clang-tidy config file
              # only 'update' a single comment in a pull request's thread.
              thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
