name: 'coverage'
on:
    pull_request:
        branches:
            - unstable
    push:
        branches:
            - unstable
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            submodules: 'recursive'
        
        - name: Downloading X11
          run: sudo apt install xorg-dev
        
        - name: Downloading Premake
          uses: BEASTSM96/premake-action@v1.3.1
        
        - name: Using Premake
          run: premake5 gmake2 --coverage
        
        - name: Build using Make
          run: make
        
        - name: Create Coverage
          run: |
            cd bin
            cd linux-x86_64
            cd Debug
            cd Testbed
            ./Testbed
            gcov ../../../../testbed/src/TestBedApp.cpp
            
        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v4.0.1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
