name: 'coverage'
on:
    pull_request:
        branches:
            - testing
    push:
        branches:
            - testing
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
          with:
            submodules: 'recursive'
        
        - name: Downloading X11
          run: sudo apt install xorg-dev
        
        - name: Downloading Premake
          uses: BEASTSM96/premake-action@v1.3.1
        
        - name: Using Premake
          run: premake5 gmake2
        
        - name: Build using Make
          run: make config=headless ccx="g++ --coverage"
        
        - name: Create Coverage
          run: |
            cd bin
            cd linux-x86_64
            cd Headless
            cd Testbed
            ./Testbed
            cd ../../../../
            cd testbed
            cd src
            gcov -o . TestBedApp.cpp
            
        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v4.0.1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}

    cpp-linter:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: cpp-linter/cpp-linter-action@v2
            id: linter
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              style: 'file'  # Use .clang-format config file
              tidy-checks: '' # Use .clang-tidy config file
              # only 'update' a single comment in a pull request's thread.
              thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
