name: Premake

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Downloading X11
      run: sudo apt install xorg-dev

    - name: Downloading Premake
      uses: BEASTSM96/premake-action@v1.3.1

    - name: Using Premake
      run: premake5 gmake2
    
    - name: Build using Make
      run: make config=headless

    - name: Run
      run: ${PWD}/bin/linux-x86_64/Headless/Testbed/Testbed
  
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        
    - name: Configure MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Downloading Premake
      uses: BEASTSM96/premake-action@v1.3.1

    - name: Using Premake
      run: premake5 vs2022
    
    - name: Build using MSBuild
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=Headless .

    - name: Test
      run: cd bin | dir
    
    - name: Run
      run: start bin/windows-x86_64/Debug/Testbed/Testbed.exe
