name: Premake

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Download Premake
      uses: BEASTSM96/premake-action@v1.3.1

    - name: Setup X11
      run: sudo apt install xorg-dev

    - name: premake
      run: premake5 gmake2
    
    - name: make
      run: make

    - name: Run
      run: ${PWD}/bin/linux-x86_64/Debug/Testbed/Testbed
